### ISSUE TITLE
pkl.load(f) ImportError for collections module

### ISSUE THREAD

**Issue by DrappierTechnologies** [nyu-dl/gated_word_char_rlm#1]
Let me start by saying awesome paper and thanks for putting the source up on github.  I had a question about an issue I've been battling for a few days now and I wanted to see if anyone else has encountered it.

I'm running on Windows 10 so I manually set the THEANO_FLAGS in my global environment variables to what's specified in the readme and I set the script arguments on my python project in Visual Studio to be the YAML's location.

When running word_char_lm.py I keep getting this:
```
Traceback (most recent call last):
  File "D:\Some\path\to\project\word_char_lm.py", line 546, in <module>
    best_valid, best_test = train(options)
  File "D:\Some\path\to\project\word_char_lm.py", line 308, in train
    word_dict = pkl.load(f) # word -> index
ImportError: No module named collections
```

So far in troubleshooting I have:
Removed Python 3.x Version and left only 2.7
Removed Anaconda Python 3.x Version and left only 2.7
Uninstalled & Reinstalled: numpy+mkl, scipy, sklearn, theano, pyyaml, libpython, & m2w64-toolchain
Tested `import collections` via python console
Debugged to make sure the yaml is being loaded and the correct values were being passed to the train function within the options parameter

Any guidance as to what could be happening would be greatly appreciated.

**Comment by DrappierTechnologies** [comment]
Nevermind, it seemed to be an issue with the compiler used to pickle the training data provided in the repo.  Anyone who has this same issue do not use the already pickled training data just repickle the training data yourself with the tools scripts provided in the repo.
